<?php

namespace Novosga\Proxies\__CG__\Novosga\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Atendimento extends \Novosga\Model\Atendimento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'codificados', 'unidade', 'servico', 'servicoUnidade', 'prioridade', 'usuario', 'usuarioTriagem', 'local', 'dataChegada', 'dataChamada', 'dataInicio', 'dataFim', 'status', 'nomeCliente', 'documentoCliente', 'siglaSenha', 'numeroSenha', 'numeroSenhaServico', 'pai', 'cliente', 'senha', 'id');
        }

        return array('__isInitialized__', 'codificados', 'unidade', 'servico', 'servicoUnidade', 'prioridade', 'usuario', 'usuarioTriagem', 'local', 'dataChegada', 'dataChamada', 'dataInicio', 'dataFim', 'status', 'nomeCliente', 'documentoCliente', 'siglaSenha', 'numeroSenha', 'numeroSenhaServico', 'pai', 'cliente', 'senha', 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Atendimento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodificados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodificados', array());

        return parent::getCodificados();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodificados(\Doctrine\Common\Collections\Collection $codificados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodificados', array($codificados));

        return parent::setCodificados($codificados);
    }

    /**
     * {@inheritDoc}
     */
    public function hash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hash', array());

        return parent::hash();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize($minimal = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array($minimal));

        return parent::jsonSerialize($minimal);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidade', array());

        return parent::getUnidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidade($unidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidade', array($unidade));

        return parent::setUnidade($unidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServico', array());

        return parent::getServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setServico($servico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServico', array($servico));

        return parent::setServico($servico);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicoUnidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicoUnidade', array());

        return parent::getServicoUnidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicoUnidade(\Novosga\Model\ServicoUnidade $servicoUnidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicoUnidade', array($servicoUnidade));

        return parent::setServicoUnidade($servicoUnidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridade', array());

        return parent::getPrioridade();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridade(\Novosga\Model\Prioridade $prioridade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridade', array($prioridade));

        return parent::setPrioridade($prioridade);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioTriagem(\Novosga\Model\Usuario $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioTriagem', array($usuario));

        return parent::setUsuarioTriagem($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioTriagem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioTriagem', array());

        return parent::getUsuarioTriagem();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', array());

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', array($local));

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChegada', array());

        return parent::getDataChegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChegada(\DateTime $dataChegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChegada', array($dataChegada));

        return parent::setDataChegada($dataChegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataChamada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataChamada', array());

        return parent::getDataChamada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataChamada(\DateTime $dataChamada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataChamada', array($dataChamada));

        return parent::setDataChamada($dataChamada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio(\DateTime $dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim(\DateTime $dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeStatus', array());

        return parent::getNomeStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeCliente', array());

        return parent::getNomeCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeCliente($nomeCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeCliente', array($nomeCliente));

        return parent::setNomeCliente($nomeCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentoCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentoCliente', array());

        return parent::getDocumentoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentoCliente($documentoCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentoCliente', array($documentoCliente));

        return parent::setDocumentoCliente($documentoCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiglaSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiglaSenha', array());

        return parent::getSiglaSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiglaSenha($siglaSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiglaSenha', array($siglaSenha));

        return parent::setSiglaSenha($siglaSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSenha', array());

        return parent::getNumeroSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSenha($numeroSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSenha', array($numeroSenha));

        return parent::setNumeroSenha($numeroSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSenhaServico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSenhaServico', array());

        return parent::getNumeroSenhaServico();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroSenhaServico($numeroSenhaServico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroSenhaServico', array($numeroSenhaServico));

        return parent::setNumeroSenhaServico($numeroSenhaServico);
    }

    /**
     * {@inheritDoc}
     */
    public function getPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPai', array());

        return parent::getPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setPai($pai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPai', array($pai));

        return parent::setPai($pai);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoEspera()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoEspera', array());

        return parent::getTempoEspera();
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoPermanencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoPermanencia', array());

        return parent::getTempoPermanencia();
    }

    /**
     * {@inheritDoc}
     */
    public function getTempoAtendimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempoAtendimento', array());

        return parent::getTempoAtendimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', array());

        return parent::toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __tostring()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__tostring', array());

        return parent::__tostring();
    }

}
